spring.application.name=Task_Manager
spring.data.mongodb.uri=mongodb+srv://sumitrathod22724:sumit123@cluster0.1bhqcmt.mongodb.net/taskmanager?retryWrites=true&w=majority&appName=Cluster0
server.port=9090